version: '3'

services:
  jenkins:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: jenkins_cicd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    ports:
      - "8081:8080"
    privileged: true
    user: root
